# Generated by Django 4.2.23 on 2025-07-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrolab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('enlaces', models.TextField(blank=True, default='No hay enlaces para esta actividad', null=True)),
                ('requisitos', models.TextField(blank=True, default='No se requieren resquisito especiales', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('docente_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrolab.docente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoactividad')),
            ],
        ),
    ]
