# Generated by Django 4.2.29 on 2026-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrolab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='descripcion',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descripcion',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
