# Generated by Django 5.1.7 on 2025-07-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Entrada')),
                ('hora_fin', models.TimeField(verbose_name='Hora Salida')),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrolab.asignatura')),
                ('carreras_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrolab.carrera')),
                ('docentes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrolab.docente')),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrolab.laboratorio')),
            ],
        ),
    ]
